# Image:
image:
    # Title: 
    title: "Sample Configuration #01"

    # User:
    user: "christopherg"

# Vulnerabilities:
vulnerabilities:
    # Forensics:
    - vulnerability:
        # Type:
        type: "Forensics"

        # Question:
        question: "What is the EUID of root?"

        # Answer:
        answer: "0"

        # Path:
        path: "/home/christopherg/Desktop/Forensics-1.txt"

        # Points:
        points: 10

        # Number:
        number: "1"

    - vulnerability:
        # Type:
        type: "Forensics"

        # Question:
        question: "What is the GID of christopherg?"

        # Answer:
        answer: "1000"

        # Path:
        path: "/home/christopherg/Desktop/Forensics-2.txt"

        # Points:
        points: 10

        # Number:
        number: "2"

    # User:
    - vulnerability:
        # Type:
        type: "UserRemoved"

        # User:
        user: "lsnart"

        # Points:
        points: 10

    - vulnerability:
        # Type:
        type: "UserCreated"

        # User:
        user: "jack"

        # Points:
        points: 10

    # Service:
    - vulnerability:
        # Type:
        type: "ServiceEnabled"

        # Service:
        service: "ufw"

        # Points:
        points: 10

    - vulnerability:
        # Type:
        type: "ServiceDisabled"

        # Service:
        service: "apparmor"

        # Points:
        points: 10

    # Configuration:
    - vulnerability:
        # Type:
        type: "FileContainsNot"

        # Path:
        path: "/etc/ssh/sshd_config"

        # Text:
        text: "PermitRootLogin yes"

        # Points:
        points: 10

        # Description:
        description: "PermitRootLogin is disabled."

    - vulnerability:
        # Type:
        type: "FileContains"

        # Path:
        path: "/etc/ssh/sshd_config"

        # Text:
        text: "UseDNS no"

        # Points:
        points: 10

        # Description:
        description: "SSH does not rely on a DNS resolver"

    # Group:
    - vulnerability:
        # Type:
        type: "UserInGroupNot"

        # User:
        user: "jack"

        # Group:
        group: "sudo"

        # Points:
        points: 10

    - vulnerability:
        # Type:
        type: "UserInGroup"

        # User:
        user: "jack"

        # Group:
        group: "fat"

        # Points:
        points: 10

    # Permissions:
    - vulnerability:
        # Type:
        type: "PermissionNot"

        # Path:
        path: "/home/christopherg/test.txt"

        # Permissions:
        permission: "0644"

        # Points:
        points: 30

    - vulnerability:
        # Type:
        type: "FileExistsNot"

        # Path:
        path: "/home/christopherg/test2.txt"

        # Points:
        points: 20


# Penalties:
penalties:
    - penalty:
        # Type:
        type: "UserRemoved"

        # User:
        user: "Tom"

        # Points:
        points: 5

        # Description:
        description: "You removed Tom! No!"
